name = "RationalApproximation"
uuid = "c83d0104-0320-462e-965e-b9bd84e5f06b"
authors = ["Junpeng Gao"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
